{% set name = "geodecision" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
  run:
    - bokeh>=1.4
    - fiona
    - geojson>=2.4.1
    - geopandas>=0.6.0
    - geopy>=1.20.0
    - jsonschema>=3.2.0
    - mapclassify>=2.1.1
    - networkx>=2.3
    - numpy>=1.17.3
    - osmnx>=0.10
    - pandas>=1.0.0
    - pyproj>=2.4.2.post1
    - rtree>=0.9.3
    - shapely>=1.6.4

test:
  imports:
    - geodecision

about:
  home: https://github.com/VCityTeam/UD-geodecision
  license: Proprietary
  license_family: Proprietary
  license_file:
  summary: Geodecision => land management and urban decision making tools
  doc_url:
  dev_url:
